"""Generate FreeBSD devd rules for TRCC devices.

FreeBSD analog of the Linux udev installer at ``_udev.py``.  Pure
string generation + atomic file I/O, called from
``BSDPlatform.setup()`` so first-run BSD users get non-root access to
the cooler over USB.

OpenBSD doesn't ship devd — it uses /dev/MAKEDEV or static permissions
managed via /etc/group.  We log a clear warning on OpenBSD pointing
the user at the right path; the same install() function is a no-op
there.
"""
from __future__ import annotations

import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path

from ...core.registry import ALL_DEVICES

log = logging.getLogger(__name__)


# FreeBSD's stock devd config dir — files in this dir are auto-loaded
# alongside /etc/devd.conf.  Some installs use /etc/devd/, some use
# /usr/local/etc/devd/; the latter is the convention for ports/pkg.
_RULES_PATH = Path("/usr/local/etc/devd/trcc.conf")


def build_devd_rules() -> str:
    """Return the full devd rules file contents for every registered device.

    Each rule chmod's the USB device node 0666 on attach so non-root
    users can claim the interface via libusb.  Pattern mirrors what the
    FreeBSD handbook and various USB-driver ports already use.
    """
    log.info("build_devd_rules: called")
    lines = [
        "# Thermalright TRCC devices — auto-generated by trcc.next setup",
        "# Removing this file reverts all registered devices to root-only",
        "",
    ]
    for (vid, pid), product in sorted(ALL_DEVICES.items()):
        lines.append(f"# {product.vendor} {product.product}")
        lines.append("notify 100 {")
        lines.append('    match "system"     "USB";')
        lines.append('    match "subsystem"  "DEVICE";')
        lines.append('    match "type"       "ATTACH";')
        lines.append(f'    match "vendor"     "0x{vid:04x}";')
        lines.append(f'    match "product"    "0x{pid:04x}";')
        lines.append('    action "chmod 0666 $cdev";')
        lines.append("};")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ── Installation ─────────────────────────────────────────────────────


def install(dry_run: bool = False) -> int:
    """Write the devd rules and reload devd.

    Returns 0 on success, non-zero on failure.  Requires root; when
    called as non-root we re-exec via sudo or doas (whichever is on
    PATH).  ``dry_run=True`` prints what would be written and returns 0.

    OpenBSD and NetBSD don't run devd — on those platforms we log a
    helpful pointer and return 0 without touching anything.
    """
    log.info("install: dry_run=%s", dry_run)
    if not _is_freebsd():
        log.warning(
            "devd installer is FreeBSD-only.  On OpenBSD, set USB device "
            "permissions via /etc/sysctl.conf and add yourself to the "
            "operator group; see doc/install/openbsd.md for the recipe.",
        )
        return 0

    rules = build_devd_rules()

    if dry_run:
        print(f"--- would write {_RULES_PATH} ---")
        print(rules, end="")
        return 0

    if os.geteuid() != 0:
        return _root_reexec()

    try:
        _write_atomic(_RULES_PATH, rules)
        log.info("Wrote %s", _RULES_PATH)
    except OSError:
        log.exception("Could not write devd config")
        return 1

    return _reload_devd()


def _is_freebsd() -> bool:
    return sys.platform.startswith("freebsd")


def _write_atomic(path: Path, content: str) -> None:
    """Write via a tmp file + rename so a crash can't leave half-written rules."""
    log.debug("_write_atomic: path=%s bytes=%d", path, len(content))
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.chmod(0o644)
    tmp.replace(path)


def _reload_devd() -> int:
    """``service devd restart`` — re-reads /usr/local/etc/devd/*.conf."""
    log.debug("_reload_devd: called")
    cmd = ["service", "devd", "restart"]
    try:
        result = subprocess.run(cmd, check=False)
    except (OSError, subprocess.SubprocessError):
        log.exception("service devd restart failed")
        return 1
    if result.returncode != 0:
        log.warning("service devd restart exited %d", result.returncode)
    return result.returncode


def _root_reexec() -> int:
    """Re-run ourselves as root via sudo or doas, whichever is on PATH.

    FreeBSD has both available depending on user setup; doas is more
    common on stripped builds.
    """
    log.info("_root_reexec: called")
    elevator = shutil.which("sudo") or shutil.which("doas")
    if elevator is None:
        log.error(
            "Neither sudo nor doas found on PATH.  Run "
            "`%s -m trcc system setup` directly as root to install devd rules.",
            sys.executable,
        )
        return 1

    code = (
        "from trcc.adapters.system._devd import install; "
        "import sys; sys.exit(install())"
    )
    cmd: list[str] = [elevator, sys.executable, "-c", code]
    log.info("Re-running as root via %s to install devd rules",
             Path(elevator).name)
    try:
        result = subprocess.run(cmd, check=False)
    except (OSError, subprocess.SubprocessError):
        log.exception("%s re-exec failed", Path(elevator).name)
        return 1
    return result.returncode
