"""Generate udev rules + usb-storage quirks for TRCC devices on Linux.

Pure string generation + atomic file I/O.  Called from
`LinuxPlatform.setup()` so first-run users get non-root access to
devices registered in `core.registry.ALL_DEVICES`.

Per-wire subsystem mapping:

    Wire   | subsystems granted 0666
    -------+-------------------------------
    SCSI   | scsi_generic, usb
    HID    | hidraw, usb
    LED    | hidraw, usb          (LED controllers are HID-based)
    BULK   | usb
    LY     | usb

Every device also gets `power/control="auto"` +
`power/autosuspend_delay_ms="10000"` so the kernel autosuspends the device
~10s after our frame stream stops; the firmware sleeps the panel in response
to the USB suspend (the mechanism the Windows app relies on — #143).  This
MUST match packaging/udev/99-trcc-lcd.rules — the two are the same rule from
two sources and drifting them re-breaks panel sleep.

For SCSI devices we additionally write /etc/modprobe.d/trcc-lcd.conf
forcing `usb-storage` Bulk-Only (not UAS) so /dev/sgN is reliably
created.
"""
from __future__ import annotations

import logging
import os
import subprocess
from pathlib import Path

from ...core.models import Wire
from ...core.registry import ALL_DEVICES
from ._elevate import reexec_as_root

log = logging.getLogger(__name__)


_RULES_PATH = Path("/etc/udev/rules.d/99-trcc-lcd.rules")
_MODPROBE_PATH = Path("/etc/modprobe.d/trcc-lcd.conf")
_MODULES_LOAD_PATH = Path("/etc/modules-load.d/trcc-sg.conf")


# Wire → which kernel subsystems grant access for that protocol.
_WIRE_SUBSYSTEMS: dict[Wire, tuple[str, ...]] = {
    Wire.SCSI: ("scsi_generic", "usb"),
    Wire.HID:  ("hidraw", "usb"),
    Wire.LED:  ("hidraw", "usb"),
    Wire.BULK: ("usb",),
    Wire.LY:   ("usb",),
}


# ── Rule generation ──────────────────────────────────────────────────


def build_udev_rules() -> str:
    """Return the full udev rules file contents (no side effects)."""
    log.info("build_udev_rules: called")
    lines = [
        "# Thermalright TRCC devices — auto-generated by trcc.next setup",
        "# Removing this file reverts all registered devices to root-only",
        "",
    ]
    for (vid, pid), product in sorted(ALL_DEVICES.items()):
        subsystems = _WIRE_SUBSYSTEMS.get(product.wire)
        if subsystems is None:
            continue
        lines.append(f"# {product.vendor} {product.product}")
        for subsystem in subsystems:
            attr = "ATTRS" if subsystem in ("hidraw", "scsi_generic") else "ATTR"
            lines.append(
                f'SUBSYSTEM=="{subsystem}", '
                f'{attr}{{idVendor}}=="{vid:04x}", '
                f'{attr}{{idProduct}}=="{pid:04x}", '
                f'MODE="0666"'
            )
        lines.append(
            f'ACTION=="add", SUBSYSTEM=="usb", '
            f'ATTR{{idVendor}}=="{vid:04x}", '
            f'ATTR{{idProduct}}=="{pid:04x}", '
            f'ATTR{{power/control}}="auto", '
            f'ATTR{{power/autosuspend_delay_ms}}="10000"'
        )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_modprobe_conf() -> str:
    """usb-storage quirks — force BOT on every SCSI device so /dev/sgN exists."""
    log.info("build_modprobe_conf: called")
    scsi_entries = [
        f"{vid:04x}:{pid:04x}:u"
        for (vid, pid), product in sorted(ALL_DEVICES.items())
        if product.wire is Wire.SCSI
    ]
    if not scsi_entries:
        return ""
    return (
        "# Thermalright TRCC SCSI LCDs — bypass UAS so /dev/sgN is created.\n"
        "# Auto-generated by trcc.next setup.\n"
        f"options usb-storage quirks={','.join(scsi_entries)}\n"
    )


# ── Installation ─────────────────────────────────────────────────────


def install(dry_run: bool = False) -> int:
    """Write the three config files and reload udev.

    Returns 0 on success, non-zero on failure.  Requires root; when
    called as non-root, re-execs via sudo.  `dry_run=True` prints what
    would be written and returns 0.
    """
    log.info("install: dry_run=%s", dry_run)
    rules = build_udev_rules()
    modprobe = build_modprobe_conf()

    if dry_run:
        print(f"--- would write {_RULES_PATH} ---")
        print(rules, end="")
        if modprobe:
            print(f"\n--- would write {_MODPROBE_PATH} ---")
            print(modprobe, end="")
        print(f"\n--- would write {_MODULES_LOAD_PATH} ---")
        print("sg\n")
        return 0

    if os.geteuid() != 0:
        return reexec_as_root(
            "from trcc.adapters.system._udev import install; sys.exit(install())"
        )

    try:
        _write_atomic(_RULES_PATH, rules)
        log.info("Wrote %s", _RULES_PATH)
        if modprobe:
            _write_atomic(_MODPROBE_PATH, modprobe)
            log.info("Wrote %s", _MODPROBE_PATH)
        _write_atomic(_MODULES_LOAD_PATH, "sg\n")
        log.info("Wrote %s (auto-load sg kernel module)", _MODULES_LOAD_PATH)
    except OSError:
        log.exception("Could not write udev/modprobe config")
        return 1

    return _reload_udev()


def _write_atomic(path: Path, content: str) -> None:
    """Write via a tmp file + rename so a crash can't leave half-written rules."""
    log.debug("_write_atomic: path=%s bytes=%d", path, len(content))
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.chmod(0o644)
    tmp.replace(path)


def _reload_udev() -> int:
    """udevadm control --reload-rules && udevadm trigger."""
    log.debug("_reload_udev: called")
    for cmd in (["udevadm", "control", "--reload-rules"],
                ["udevadm", "trigger", "--subsystem-match=usb"],
                ["udevadm", "trigger", "--subsystem-match=scsi_generic"],
                ["udevadm", "trigger", "--subsystem-match=hidraw"]):
        try:
            result = subprocess.run(cmd, check=False)
        except (OSError, subprocess.SubprocessError):
            log.exception("udevadm command failed: %s", cmd)
            return 1
        if result.returncode != 0:
            log.warning("udevadm exit %d: %s", result.returncode, " ".join(cmd))
    return 0


